// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg1GRgB5q0ZXbr8z2SjrAYG4Ijvs2o0Xg',
    appId: '1:288807197516:web:ebe652b24e68b7da84cde9',
    messagingSenderId: '288807197516',
    projectId: 'socialmediaapp-104e1',
    authDomain: 'socialmediaapp-104e1.firebaseapp.com',
    storageBucket: 'socialmediaapp-104e1.appspot.com',
    measurementId: 'G-409KBD56NH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhxBJ3rnFgGTNaRcPx1ryv3U9IymK704w',
    appId: '1:288807197516:android:1bfafcfdf938ab0a84cde9',
    messagingSenderId: '288807197516',
    projectId: 'socialmediaapp-104e1',
    storageBucket: 'socialmediaapp-104e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbo870PuaawVAU16msH4yJK1MEEaidXZQ',
    appId: '1:288807197516:ios:af4cd42f90efa34084cde9',
    messagingSenderId: '288807197516',
    projectId: 'socialmediaapp-104e1',
    storageBucket: 'socialmediaapp-104e1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbo870PuaawVAU16msH4yJK1MEEaidXZQ',
    appId: '1:288807197516:ios:af4cd42f90efa34084cde9',
    messagingSenderId: '288807197516',
    projectId: 'socialmediaapp-104e1',
    storageBucket: 'socialmediaapp-104e1.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg1GRgB5q0ZXbr8z2SjrAYG4Ijvs2o0Xg',
    appId: '1:288807197516:web:81895d66db1b9f6e84cde9',
    messagingSenderId: '288807197516',
    projectId: 'socialmediaapp-104e1',
    authDomain: 'socialmediaapp-104e1.firebaseapp.com',
    storageBucket: 'socialmediaapp-104e1.appspot.com',
    measurementId: 'G-MZT9JN5DFB',
  );
}
